hw10_project/hw10_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls'))
]

hw10_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path("add_quote/", views.add_quote, name="add_quote"),
    path("add_author/", views.add_author, name="add_author"),
    path("author/<int:author_id>", views.author, name="author"),
]

hw10_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                     redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw10_project/quotes/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.CharField(max_length=100)
    born_location = models.CharField(max_length=120)
    bio = models.TextField()

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw10_project/users/models.py
from django.db import models

# Create your models here.

hw10_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, DateInput, ModelChoiceField, \
    ModelMultipleChoiceField, Select, SelectMultiple
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, widget=TextInput(attrs={'class': 'form-control'}))
    born_date = DateField(widget=DateInput(attrs={'class': 'form-control'}))
    born_location = CharField(max_length=100, widget=TextInput(attrs={'class': 'form-control'}))
    bio = CharField(max_length=500, widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Author
        fields = ('fullname', 'born_date', 'born_location', 'bio')


class TagForm(ModelForm):
    class TagForm(ModelForm):
        name = CharField(max_length=25, required=True, widget=TextInput(attrs={'class': 'form-control'}))

        class Meta:
            model = Tag
            fields = ['name']


class QuoteForm(ModelForm):
    quote = CharField(max_length=1000, widget=TextInput(attrs={'class': 'form-control'}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'),
                              widget=Select(attrs={"class": "form-select"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'),
                                    widget=SelectMultiple(attrs={"class": "form-select", "size": "7"}))

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

hw10_project/users/forms.py
from django.contrib.auth.models import User
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    first_name = CharField(max_length=150, widget=TextInput(attrs={'class': 'form-control'}))
    last_name = CharField(max_length=150, widget=TextInput(attrs={'class': 'form-control'}))
    email = EmailField(max_length=150, required=True, widget=EmailInput(attrs={'class': 'form-control'}))
    password1 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    password = CharField(max_length=12, min_length=8, required=True,
                         widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'password')

hw10_project/quotes/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import AuthorForm, QuoteForm, TagForm
from .models import Author, Quote, Tag
# Create your views here.
from .utils import get_mongodb


def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page})


@login_required
def add_quote(request):
    form = QuoteForm(instance=Quote())
    if request.method == 'POST':
        form = QuoteForm(request.POST, instance=Quote())
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
    return render(request, 'quotes/add_quote.html',
                  context={'title': 'Quotes to Scrape', 'form': form})


@login_required
def add_author(request):
    form = AuthorForm(instance=Author())
    if request.method == 'POST':
        form = AuthorForm(request.POST, instance=Author())
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
    return render(request, 'quotes/add_author.html',
                  context={'title': 'Quotes to Scrape', 'form': form})


def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, "quotes/author.html", {"author": author})

hw10_project/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='quotes:root')
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Your account {username} is created successfully!')
            return redirect(to='users:login')
        return render(request, self.template_name, {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

hw10_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div mb-3>
        <label class="form-label"> Fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div mb-3>
        <label class="form-label"> Born Date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date}}</span>
    </div>
    <div mb-3>
        <label class="form-label"> Born Location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div mb-3>
        <label class="form-label"> Description:
            {{ form.bio }}
        </label>
        <span>{{ form.errors.bio }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
    </div>
</form>
{% endblock %}

hw10_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
<h1>Add new quote</h1>
<form action="{% url 'quotes:add_quote' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Quote</label>
        {{form.quote}}
    </div>
    <div class="mb-3">
        <label class="form-label">Author</label>
        {{form.author}}
    </div>
    <div class="mb-3">
        <label class="form-control">Select tags:</label>
        {{ form.tags }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

hw10_project/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}
{% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span>
        <span
                class="author-born-location">{{author.born_location}}
        </span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description"> {{author.bio}}</div>
</div>

{% endblock %}

hw10_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework10</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>

            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'quotes:add_author' %}" class="nav-link">Add author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="nav-link">Add quote</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                    {% else %}
                    <a href="{% url 'users:register' %}" class="btn btn-primary">SingUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>


{% block content %} {% endblock %}

    </div>
</body>
</html>

hw10_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
          {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{quote.author}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags %}
            <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
            {% endfor %}

        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>


            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>

        </ul>
    </nav>
    </div>

</div>

{% endblock %}}

hw10_project/users/templates/users/logout.html
{% extends "quotes/base.html" %}

{% block content %}
<div>
    <h2>Log Out</h2>
</div>

{% endblock %}

hw10_project/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw10_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset completed!</h2>

{% endblock %}

hw10_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw10_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw10_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}>

hw10_project/users/templates/users/signin.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign In</h2>
</div>
<!--Виводимо Flash сповіщення-->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<!-- Обробляємо помилки форми, які не належать до полів -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label"> Username:</label>
            {{ form.username }}
        </div>
        <span>{{ form.errors.username }}</span>
        <div class="mb-3">
            <label class="form-label"> Password:</label>
            {{ form.password }}
        </div>
        <span>{{ form.errors.password }}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sign In</button>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

hw10_project/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label"> Username:</label>
            {{ form.username }}
        </div>
        <span>{{ form.errors.username }}</span>
        <div class="mb-3">
            <label class="form-label"> First Name:</label>
            {{ form.first_name }}
        </div>
        <span>{{ form.errors.first_name }}</span>
        <div class="mb-3">
            <label class="form-label"> Last Name:</label>
            {{ form.last_name }}
        </div>
        <span>{{ form.errors.last_name }}</span>
        <div class="mb-3">
            <label class="form-label"> Email:</label>
            {{ form.email }}
        </div>
        <span>{{ form.errors.email }}</span>
        <div class="mb-3">
            <label class="form-label"> Password:</label>
            {{ form.password1 }}
        </div>
        <span>{{ form.errors.password1 }}</span>
        <div class="mb-3">
            <label class="form-label"> Password confirmation:</label>
            {{ form.password2 }}
        </div>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>

</form>
{% endblock %}